# Generated by Django 2.1.2 on 2018-10-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
