# Generated by Django 2.1.2 on 2018-11-09 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181109_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='doc_identidad',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[VEF]-\\d+$', 'Formato de documento de identidad inválido. Los números deben estar precedidos por V- o E-.')], verbose_name='Documento de Identidad'),
        ),
    ]
