# Generated by Django 2.1.2 on 2018-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181112_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='proyecto_seleccionado',
            field=models.IntegerField(default=-1),
        ),
    ]
