# Generated by Django 2.1.2 on 2018-11-14 20:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('M2', 'Menos de 2 años'), ('M2-5', '2 a 5 años'), ('M5-10', '5 a 10 años'), ('M10', 'Mas de 10 años')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40, unique=True)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', error_messages={'unique': 'Ya existe un Estudio con el nombre colocado'}, max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('FS', 'Fisico'), ('BIO', 'Biologico'), ('SC', 'Socio-Cultural')], default='', max_length=50)),
                ('valoracion_relevancia', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='', max_length=6)),
                ('tipo_relevancia', models.CharField(choices=[('DI', 'Directo'), ('IN', 'Indirecto')], default='', max_length=50)),
                ('pondIntensidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondExtension', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondDuracion', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondReversibilidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pondProbabilidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('via', models.FloatField(default=0.0)),
                ('duracion', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Duracion')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('GE', 'Generalizada (>75%)'), ('EX', 'Extensiva (35-74%)'), ('LO', 'Local (10-34%)'), ('PU', 'Puntual (<10%)')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40, unique=True)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia', models.CharField(choices=[('MA', 'Muy Alta'), ('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40, unique=True)),
                ('minimo', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('maximo', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sociocultural', models.CharField(choices=[('MA', 'Muy Alto'), ('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('grado_perturbacion', models.CharField(choices=[('F', 'Fuerte'), ('M', 'Medio'), ('S', 'Suave')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Probabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja'), ('N', 'Nula')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40, unique=True)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Reversibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('IR', 'Irreversible'), ('TR', 'Requiere Tratamiento'), ('MR', 'Medianamente Reversible'), ('RE', 'Reversible')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40, unique=True)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='intensidad',
            unique_together={('valor_sociocultural', 'grado_perturbacion')},
        ),
        migrations.AddField(
            model_name='estudio',
            name='extension',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Extension'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='importancia_estudio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Importancia'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='intensidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Intensidad'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='probabilidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Probabilidad'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='reversibilidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Reversibilidad'),
        ),
    ]
