# Generated by Django 2.2.dev20180914183443 on 2018-10-29 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='importancia_estudio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Importancia'),
        ),
    ]
