# Generated by Django 2.0.1 on 2018-10-30 01:24

from django.db import migrations
app_name = "configuracion"
def _data_inicial(apps, schema_editor):
    
    #intensidad
    Intensidad = apps.get_model(app_name, 'Intensidad')
    insert_a = []
    insert_a.append(Intensidad(valor_sociocultural="MA", grado_perturbacion="F" ,valor=10))
    insert_a.append(Intensidad(valor_sociocultural="MA", grado_perturbacion="M" ,valor=7))
    insert_a.append(Intensidad(valor_sociocultural="MA", grado_perturbacion="S" ,valor=5))
    insert_a.append(Intensidad(valor_sociocultural="A", grado_perturbacion="F" ,valor=7))
    insert_a.append(Intensidad(valor_sociocultural="A", grado_perturbacion="M" ,valor=7))
    insert_a.append(Intensidad(valor_sociocultural="A", grado_perturbacion="S" ,valor=5))
    insert_a.append(Intensidad(valor_sociocultural="M", grado_perturbacion="F" ,valor=5))
    insert_a.append(Intensidad(valor_sociocultural="M", grado_perturbacion="M" ,valor=5))
    insert_a.append(Intensidad(valor_sociocultural="M", grado_perturbacion="S" ,valor=2))
    insert_a.append(Intensidad(valor_sociocultural="B", grado_perturbacion="F" ,valor=2))
    insert_a.append(Intensidad(valor_sociocultural="B", grado_perturbacion="M" ,valor=2))
    insert_a.append(Intensidad(valor_sociocultural="B", grado_perturbacion="S" ,valor=2))
  
    #extension
    Extension = apps.get_model(app_name, 'Extension')
    insert_a.append(Extension(clasificacion="GE", valor=10))
    insert_a.append(Extension(clasificacion="EX", valor=7))
    insert_a.append(Extension(clasificacion="LO", valor=5))
    insert_a.append(Extension(clasificacion="PU", valor=2))

    #duracion
    Duracion = apps.get_model(app_name, 'Duracion')
    insert_a.append(Duracion(criterio="M2", valor=2))
    insert_a.append(Duracion(criterio="M2-5", valor=5))
    insert_a.append(Duracion(criterio="M5-10", valor=7))
    insert_a.append(Duracion(criterio="M10", valor=10))

    #extension
    Reversibilidad = apps.get_model(app_name, 'Reversibilidad')
    insert_a.append(Reversibilidad(clasificacion="IR", valor=10))
    insert_a.append(Reversibilidad(clasificacion="TR", valor=7))
    insert_a.append(Reversibilidad(clasificacion="MR", valor=5))
    insert_a.append(Reversibilidad(clasificacion="RE", valor=2))
	
    #probabilidad
    Probabilidad = apps.get_model(app_name, 'Probabilidad')
    insert_a.append(Probabilidad(probabilidad="A",valor=10))
    insert_a.append(Probabilidad(probabilidad="M",valor=6))
    insert_a.append(Probabilidad(probabilidad="B",valor=4))
    insert_a.append(Probabilidad(probabilidad="N",valor=0))
	
    #importancia
    Importancia = apps.get_model(app_name, 'Importancia')
    insert_a.append(Importancia(importancia="MA",minimo=8,maximo=10,valor=10))
    insert_a.append(Importancia(importancia="A",minimo=6,maximo=7.9,valor=7))
    insert_a.append(Importancia(importancia="M",minimo=3,maximo=5.9,valor=5))
    insert_a.append(Importancia(importancia="B",minimo=0,maximo=2.9,valor=2))
	
    for x in insert_a:
        x.save()
	

class Migration(migrations.Migration):

    dependencies = [
        (app_name, '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_data_inicial),
    ]
