# Generated by Django 2.2.dev20180914183443 on 2018-10-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20181030_0137'),
        ('configuracion', '0002_estudio_importancia_estudio'),
    ]

    operations = [
    ]
