# Generated by Django 2.2.dev20180914183443 on 2018-10-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_merge_20181030_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duracion',
            name='criterio',
            field=models.CharField(choices=[('M2', 'Menos de 2 años'), ('M2-5', '2 a 5 años'), ('M5-10', '5 a 10 años'), ('M10', 'Mas de 10 años')], default='', error_messages={'max_length': 'El nombre no puede pasar de mas de 40 caracteres'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='duracion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Duracion'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='extension',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Extension'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='intensidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Intensidad'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='probabilidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Probabilidad'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='reversibilidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Reversibilidad'),
        ),
    ]
