# Generated by Django 2.1.2 on 2018-11-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20181030_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(default='', error_messages={'unique': 'Ya existe un Estudio con el nombre colocado'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='valoracion_relevancia',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='', max_length=6),
        ),
    ]
