# Generated by Django 2.1.2 on 2018-11-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20181101_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=40)),
                ('descripcion', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', error_messages={'unique': 'Ya existe un Macro con ese nombre  colocado'}, max_length=40, unique=True)),
                ('descripcion', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', error_messages={'unique': 'Ya existe un Macro con ese nombre  colocado'}, max_length=40, unique=True)),
                ('descripcion', models.CharField(default='', max_length=40)),
                ('proyecto', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='macro',
            unique_together={('nombre', 'proyecto')},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='macro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Macro'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nombre', 'macro')},
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('nombre', 'disciplina')},
        ),
    ]
