# Generated by Django 2.1.2 on 2018-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_auto_20181113_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='macro',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
    ]
