# Generated by Django 2.1.2 on 2018-11-14 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_auto_20181114_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='disciplina',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Disciplina'),
        ),
    ]
