# Generated by Django 2.1.2 on 2018-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_auto_20181113_1411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='macro',
        ),
        migrations.DeleteModel(
            name='Macro',
        ),
        migrations.AddField(
            model_name='actividad',
            name='macro',
            field=models.CharField(choices=[('PI', 'Proceso de Inicio'), ('PP', 'Proceso de Planificación'), ('PE', 'Proceso de Ejecucion'), ('PCS', 'Proceso de Control y Seguimiento'), ('PC', 'Proceso de Cierre')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='disciplina',
            field=models.CharField(choices=[('IN', 'Integración'), ('SK', 'Stakeholder'), ('AL', 'Alcance'), ('RE', 'Recurso'), ('TI', 'Tiempo'), ('CO', 'Costo'), ('RI', 'Riesgo'), ('CA', 'Calidad'), ('AD', 'Adquisición'), ('COM', 'Comunicación')], default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('nombre', 'proyecto')},
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
