# Generated by Django 2.1.2 on 2018-11-16 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20181114_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='amenazas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
