# Generated by Django 2.1.2 on 2018-11-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20181114_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=40)),
                ('descripcion', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=40)),
                ('descripcion', models.CharField(default='', max_length=40)),
                ('proyecto', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='actividad',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='macro',
            unique_together={('nombre', 'proyecto')},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='macro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='configuracion.Macro'),
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='macro',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='proyecto',
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nombre', 'macro')},
        ),
    ]
