# Generated by Django 2.1.2 on 2018-11-16 03:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_auto_20181116_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='amenazas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default='list', size=None),
        ),
    ]
