# Generated by Django 2.1.2 on 2018-11-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_auto_20181116_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='amenazas',
            field=models.CharField(default='', max_length=100),
        ),
    ]
