# Generated by Django 2.1.2 on 2018-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_auto_20181116_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='amenazas',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
