# Generated by Django 2.0.1 on 2018-12-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0015_auto_20181201_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='medidas',
        ),
    ]
