# Generated by Django 2.1.2 on 2018-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_auto_20181201_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='tiempo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
