# Generated by Django 2.1.2 on 2018-12-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_subplan_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='plan',
        ),
    ]
