# Generated by Django 2.0.1 on 2018-12-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_auto_20181201_1532'),
        ('configuracion', '0019_remove_subplan_plan'),
    ]

    operations = [
    ]
