# Generated by Django 2.1.2 on 2018-12-05 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0021_auto_20181202_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='plan_principal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='configuracion.Plan'),
        ),
    ]
