# Generated by Django 2.1.2 on 2018-10-28 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Nombre incorrecto', 'invalid')])),
                ('apellido', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Apellido incorrecto', 'invalid')])),
                ('cedula', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(re.compile('/^[V|E|J|P][0-9]{5,9}$/'), 'Cédula incorrecta', 'invalid')])),
                ('pasaporte', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.TextField()),
                ('area', models.TextField()),
                ('tipo', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(choices=[('natural', 'Persona natural'), ('juridica', 'Persona Jurídica')], max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('rif', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^([VEJPGvejpg]{1})-([0-9]{8})-([0-9]{1}$)'), 'RIF incorrecto', 'invalid')])),
                ('direccion', models.TextField()),
                ('nombre_representante_legal', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Nombre incorrecto', 'invalid')])),
                ('apellido_representante_legal', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Apellido incorrecto', 'invalid')])),
                ('cedula_representante_legal', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^[V|E|J|P][0-9]{5,9}$'), 'Cédula incorrecta', 'invalid')])),
                ('pasaporte_representante_legal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('telefono', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]{11}$'), 'Teléfono incorrecto', 'invalid')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.Datos_Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.Datos_Persona')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='datos_persona',
            unique_together={('cedula', 'pasaporte')},
        ),
    ]
