# Generated by Django 2.1.2 on 2018-10-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_Persona',
            new_name='DatosPersona',
        ),
        migrations.RenameModel(
            old_name='Datos_Proyecto',
            new_name='DatosProyecto',
        ),
    ]
