# Generated by Django 2.1.2 on 2018-11-16 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objGeneral', models.TextField()),
                ('objEspecifico', models.TextField()),
                ('justificacion', models.TextField()),
                ('area', models.ImageField(upload_to='')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto')),
            ],
        ),
    ]
