# Generated by Django 2.1.2 on 2018-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosproyecto',
            name='marco_juridico',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datosproyecto',
            name='marco_metodologico',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datosproyecto',
            name='marco_teorico',
            field=models.TextField(null=True),
        ),
    ]
