# Generated by Django 2.1.2 on 2018-11-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0002_descripcionproyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descripcionproyecto',
            old_name='objEspecifico',
            new_name='obj_especifico',
        ),
        migrations.RenameField(
            model_name='descripcionproyecto',
            old_name='objGeneral',
            new_name='obj_general',
        ),
    ]
