# Generated by Django 2.0.9 on 2018-10-28 22:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0003_datosdocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='apellido',
            field=models.CharField(default='Rodriguez', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Apellido incorrecto', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='cedula',
            field=models.CharField(default=12345678, max_length=8, validators=[django.core.validators.RegexValidator(re.compile('/^[V|E|J|P][0-9]{5,9}$/'), 'Cédula incorrecta', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='nivel_academico',
            field=models.CharField(default='Default Nivel Academico', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='nombre',
            field=models.CharField(default='Pedro', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Nombre incorrecto', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='pasaporte',
            field=models.IntegerField(default=123456789, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='tipo_responsable',
            field=models.CharField(choices=[('EsIA', 'Especialista del EsIA'), ('fisico', 'Especialista del Medio Físico'), ('biologico', 'Especialista del Medio Biológico'), ('socioeconomico', 'Especialista del Medio Socioeconómico'), ('gerente', 'Gerente del Proyecto de Desarrollo')], default='EsIA', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='apellido',
            field=models.CharField(default='Diaz', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Apellido incorrecto', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='cedula',
            field=models.CharField(default=12345678, max_length=8, validators=[django.core.validators.RegexValidator(re.compile('/^[V|E|J|P][0-9]{5,9}$/'), 'Cédula incorrecta', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='nombre',
            field=models.CharField(default='Luis', max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+\\s]+$'), 'Nombre incorrecto', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='pasaporte',
            field=models.IntegerField(default=123456789, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='telefono',
            field=models.CharField(default='04141234567', max_length=11, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]{11}$'), 'Teléfono incorrecto', 'invalid')]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='responsable',
        ),
        migrations.AlterUniqueTogether(
            name='responsable',
            unique_together={('cedula', 'pasaporte')},
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='solicitante',
        ),
        migrations.AlterUniqueTogether(
            name='solicitante',
            unique_together={('cedula', 'pasaporte')},
        ),
    ]
