# Generated by Django 2.1.2 on 2018-11-25 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0004_auto_20181118_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedioFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fisico', 'Medio físico'), ('biologico', 'Medio biológico'), ('socio', 'Medio sociocultural')], max_length=100)),
                ('descripcion', models.TextField()),
                ('conclusiones', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SubaracteristicaMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSub', models.CharField(max_length=100)),
                ('atributo', models.TextField()),
                ('comentario', models.TextField()),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.CaracteristicaMedio')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicamedio',
            name='medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.MedioFisico'),
        ),
        migrations.AlterUniqueTogether(
            name='subaracteristicamedio',
            unique_together={('nombreSub', 'caracteristica')},
        ),
        migrations.AlterUniqueTogether(
            name='mediofisico',
            unique_together={('tipo', 'proyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='caracteristicamedio',
            unique_together={('caracteristica', 'medio')},
        ),
    ]
