# Generated by Django 2.1.2 on 2018-11-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0004_auto_20181118_2342'),
        ('eia_app', '0002_auto_20181115_1631'),
    ]

    operations = [
    ]
