# Generated by Django 2.0.9 on 2018-10-28 23:25

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0004_auto_20181028_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='cedula',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^[V|E|J|P][0-9]{5,9}$'), 'Cédula incorrecta', 'invalid')]),
        ),
    ]
