# Generated by Django 2.1.2 on 2018-12-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0005_merge_20181126_1537'),
        ('eia_app', '0005_recomendacionproyecto'),
    ]

    operations = [
    ]
