# Generated by Django 2.0.9 on 2018-10-29 00:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0005_auto_20181028_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='cedula',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^[V|E|J|P][0-9]{5,9}$'), 'Cédula incorrecta', 'invalid')]),
        ),
    ]
