# Generated by Django 2.1.2 on 2018-11-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0006_auto_20181125_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaracteristicamedio',
            old_name='nombreSub',
            new_name='nombre_sub',
        ),
        migrations.AlterUniqueTogether(
            name='subaracteristicamedio',
            unique_together={('nombre_sub', 'caracteristica')},
        ),
    ]
