# Generated by Django 2.1.2 on 2018-12-10 05:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0007_conclusionproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersona',
            name='cedula',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^[V|E|J|P][0-9]{5,9}$'), 'Cédula incorrecta', 'invalid')]),
        ),
    ]
