# Generated by Django 2.1.2 on 2018-12-09 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0007_auto_20181126_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoHumano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.TextField()),
                ('cantidad', models.TextField()),
                ('tiempo', models.CharField(max_length=100)),
                ('monto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='CostoMateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_unidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('humano', 'Talento Humano'), ('profesionales', 'Servicios Profesionales y Técnicos'), ('hospedaje', 'Pasajes y Hospedaje'), ('materiales', 'Recursos Materiales'), ('oficina', 'Materiales de Oficina'), ('insumos', 'Insumos')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='costomateriales',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.TipoCosto'),
        ),
        migrations.AddField(
            model_name='costohumano',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eia_app.TipoCosto'),
        ),
    ]
