# Generated by Django 2.1.2 on 2018-10-29 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0007_auto_20181029_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='pasaporte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='pasaporte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
