# Generated by Django 2.1.2 on 2018-12-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0008_auto_20181209_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costohumano',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eia_app.TipoCosto'),
        ),
        migrations.AlterField(
            model_name='costomateriales',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eia_app.TipoCosto'),
        ),
    ]
