# Generated by Django 2.1.2 on 2018-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0008_auto_20181029_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='tipo_responsable',
            field=models.CharField(choices=[('EsIA', 'Especialista del EsIA'), ('fisico', 'Especialista del Medio Físico'), ('biologico', 'Especialista del Medio Biológico'), ('socioeconomico', 'Especialista del Medio Socioeconómico'), ('gerente', 'Gerente del Proyecto de Desarrollo')], max_length=16),
        ),
    ]
