# Generated by Django 2.1.2 on 2018-12-12 03:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0008_auto_20181210_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersona',
            name='cedula',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(re.compile('/^[V|E|J|P][0-9]{5,9}$/'), 'Cédula incorrecta', 'invalid')]),
        ),
    ]
