# Generated by Django 2.1.2 on 2019-01-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0009_auto_20181210_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosproyecto',
            name='url',
        ),
    ]
