# Generated by Django 2.1.2 on 2018-10-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0009_auto_20181029_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eia_app.DatosProyecto'),
            preserve_default=False,
        ),
    ]
