# Generated by Django 2.1.2 on 2018-12-30 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eia_app', '0010_auto_20181212_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosproyecto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datospersona',
            name='cedula',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^[V|E|J|P][0-9]{5,9}$'), 'Cédula incorrecta', 'invalid')]),
        ),
    ]
