# Generated by Django 2.1.2 on 2019-01-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0010_remove_datosproyecto_url'),
        ('eia_app', '0011_auto_20190107_2106'),
    ]

    operations = [
    ]
