# Generated by Django 2.1.2 on 2018-12-29 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0012_datosproyecto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproyecto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
