# Generated by Django 2.1.2 on 2019-01-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eia_app', '0012_merge_20190107_2150'),
        ('eia_app', '0011_auto_20181230_1545'),
    ]

    operations = [
    ]
